#!/usr/bin/env bash
# install.sh — one-shot installer for the provbok app on Ubuntu 22.04 / 24.04
# (also works on Debian 12). Run as root.
#
# Usage:
#   sudo PROVBOK_DOMAIN=provbok.example.se PROVBOK_EMAIL=you@example.com \
#        PROVBOK_REPO=https://github.com/wearefaces/provbokning.git \
#        bash install.sh
#
# Optional vars (sensible defaults shown):
#   PROVBOK_USER=provbok        # system user that runs the app
#   PROVBOK_DIR=/opt/provbok    # install root
#   PROVBOK_BRANCH=main
#   LOGIN_USER / LOGIN_PASS     # if set, written into /etc/provbok.env
#   SMS_API_USERNAME / SMS_API_PASSWORD
#
# What it does:
#   1. apt-installs python3, git, nginx, certbot, the nginx-certbot plugin
#   2. Creates a system user 'provbok' with no shell
#   3. Clones the repo to /opt/provbok/app and makes a venv at /opt/provbok/venv
#   4. Writes /etc/provbok.env with secrets
#   5. Installs and enables a systemd service (deploy/provbok.service)
#   6. Configures nginx as a reverse proxy and obtains a Let's Encrypt cert

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Run as root (sudo bash install.sh)" >&2
    exit 1
fi

: "${PROVBOK_DOMAIN:?Set PROVBOK_DOMAIN, e.g. provbok.example.se}"
: "${PROVBOK_EMAIL:?Set PROVBOK_EMAIL for Lets Encrypt notifications}"
PROVBOK_REPO="${PROVBOK_REPO:-https://github.com/wearefaces/provbokning.git}"
PROVBOK_BRANCH="${PROVBOK_BRANCH:-main}"
PROVBOK_USER="${PROVBOK_USER:-provbok}"
PROVBOK_DIR="${PROVBOK_DIR:-/opt/provbok}"

APP_DIR="$PROVBOK_DIR/app"
VENV_DIR="$PROVBOK_DIR/venv"
DATA_DIR="$PROVBOK_DIR/data"
ENV_FILE="/etc/provbok.env"

echo "==> Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y --no-install-recommends \
    git python3 python3-venv python3-pip ca-certificates \
    nginx certbot python3-certbot-nginx ufw

echo "==> Creating service user '$PROVBOK_USER'"
if ! id -u "$PROVBOK_USER" >/dev/null 2>&1; then
    useradd --system --home-dir "$PROVBOK_DIR" --shell /usr/sbin/nologin "$PROVBOK_USER"
fi

echo "==> Cloning repo to $APP_DIR"
mkdir -p "$PROVBOK_DIR"
if [[ -d "$APP_DIR/.git" ]]; then
    git -C "$APP_DIR" fetch --depth 1 origin "$PROVBOK_BRANCH"
    git -C "$APP_DIR" reset --hard "origin/$PROVBOK_BRANCH"
else
    git clone --depth 1 --branch "$PROVBOK_BRANCH" "$PROVBOK_REPO" "$APP_DIR"
fi

echo "==> Creating Python venv"
python3 -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --upgrade pip wheel
"$VENV_DIR/bin/pip" install -r "$APP_DIR/requirements.txt"

echo "==> Preparing data directory"
mkdir -p "$DATA_DIR"
# Seed config.json once if missing
if [[ ! -f "$DATA_DIR/config.json" && -f "$APP_DIR/config.json" ]]; then
    cp "$APP_DIR/config.json" "$DATA_DIR/config.json"
fi
chown -R "$PROVBOK_USER:$PROVBOK_USER" "$PROVBOK_DIR"

echo "==> Writing $ENV_FILE"
SECRET_KEY="${SECRET_KEY:-$(python3 -c 'import secrets;print(secrets.token_hex(32))')}"
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by deploy/install.sh
DATA_DIR=$DATA_DIR
SECRET_KEY=$SECRET_KEY
COOKIE_SECURE=1
${LOGIN_USER:+LOGIN_USER=$LOGIN_USER}
${LOGIN_PASS:+LOGIN_PASS=$LOGIN_PASS}
${SMS_API_USERNAME:+SMS_API_USERNAME=$SMS_API_USERNAME}
${SMS_API_PASSWORD:+SMS_API_PASSWORD=$SMS_API_PASSWORD}
EOF
chown root:"$PROVBOK_USER" "$ENV_FILE"
chmod 640 "$ENV_FILE"
umask 022

echo "==> Installing systemd unit"
install -m 0644 "$APP_DIR/deploy/provbok.service" /etc/systemd/system/provbok.service
systemctl daemon-reload
systemctl enable --now provbok.service

echo "==> Configuring nginx site for $PROVBOK_DOMAIN"
sed "s/__DOMAIN__/$PROVBOK_DOMAIN/g" "$APP_DIR/deploy/nginx.conf" \
    > /etc/nginx/sites-available/provbok
ln -sf /etc/nginx/sites-available/provbok /etc/nginx/sites-enabled/provbok
# Disable the default site if it's still there
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

echo "==> Configuring firewall (ufw)"
if ufw status | grep -q "Status: inactive"; then
    ufw --force enable
fi
ufw allow OpenSSH || true
ufw allow 'Nginx Full' || true

echo "==> Requesting Let's Encrypt certificate for $PROVBOK_DOMAIN"
certbot --nginx --non-interactive --agree-tos --redirect \
    --email "$PROVBOK_EMAIL" -d "$PROVBOK_DOMAIN"

echo
echo "============================================================"
echo " Done!  Visit:  https://$PROVBOK_DOMAIN"
echo
echo " Useful commands:"
echo "   systemctl status  provbok"
echo "   journalctl -u    provbok -f"
echo "   sudoedit         $ENV_FILE   # change secrets, then:"
echo "   systemctl restart provbok"
echo
echo " To update after a 'git push' to GitHub, run:"
echo "   sudo bash $APP_DIR/deploy/update.sh"
echo "============================================================"
